- name: cinnamon
  version:
  previous:
  plugin: github
  url: https://github.com/linuxmint/cinnamon
  maintainer: MargueriteSu
  email: marguerite#opensuse.org
  unstable: false
  genchange: true
  mtime: 2019-03-31 13:19:00
  nondigit: true
